#!/bin/bash

set -o errexit

export LC_ALL=en_US.utf8
export LANGUAGE=en_US.utf8
export LANG=en_US.utf8

PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

echo "* Get latest"
apt-get -y update
apt-get -y upgrade
apt-get -y dist-upgrade

echo "* Disable and remove rpcbind"
apt-get -y remove rpcbind || true
systemctl stop rpcbind.service
systemctl disable rpcbind.service

echo "* Disable nfs-client"
systemctl unmask nfs-client.target
systemctl disable nfs-client.target

echo "* stop and remove ssh service"
systemctl stop sshd.service
systemctl disable sshd.service

echo "* Get minio for linux"
curl -LO https://dl.min.io/server/minio/release/linux-amd64/minio
chmod +x minio
mv minio /usr/local/bin/minio

curl -LO https://dl.min.io/client/mc/release/linux-amd64/mc
chmod +x mc
mv mc /usr/local/bin/mc

echo "* Setup nginx"
mv /etc/nginx/nginx.conf /etc/nginx/nginx.conf.bak
mv /usr/local/var/tmp/nginx.conf /etc/nginx/nginx.conf
ln -nfs /etc/nginx/sites-available/minio.conf /etc/nginx/sites-enabled/minio.conf
systemctl restart nginx || true

echo "* Create bash-history"
cat >> /root/.bash_history << EOF
nginx -t
systemctl restart nginx
systemctl status nginx
vim /etc/default/minio
systemctl restart minio
systemctl status minio
systemctl edit --full minio
systemctl daemon-reload
systemctl reset-failed minio
journalctl --since $(date '+%Y-%m-%d')
EOF

echo "* Ensure bootstrap will run next time"
rm -rf /var/lib/bootstrap

echo "* Cleaning up."
rm /root/customize
history -c
